// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProjetGL.Migrations
{
    [DbContext(typeof(ProjetGLContext))]
    [Migration("20211221140058_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProjetGL.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcronymeClub")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassementEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifferencedeBut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEntraineur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEquipe")
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreDefaite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreNul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreVictoire")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ProjetGL.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeJoueur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ButJoueur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartonJaune")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartonRouge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchJouee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationaliteJoueur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomJoueur")
                        .HasColumnType("TEXT");

                    b.Property<int>("PasseDecisiveJoueur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosteJoueur")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomJoueur")
                        .HasColumnType("TEXT");

                    b.Property<double>("TailleJoueur")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Joueur");
                });

            modelBuilder.Entity("ProjetGL.Models.Joueur", b =>
                {
                    b.HasOne("ProjetGL.Models.Equipe", "Equipe")
                        .WithMany("LesJoueurs")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ProjetGL.Models.Equipe", b =>
                {
                    b.Navigation("LesJoueurs");
                });
#pragma warning restore 612, 618
        }
    }
}
